security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/clients, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/factures, roles: IS_AUTHENTICATED_ANONYMOUSLY }
