version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony
    environment:
      - DATABASE_URL=mysql://symfony:symfony@db:3306/crm_db?serverVersion=8.0
    command: sh -c "composer install && php-fpm -F"
    healthcheck:
      test: ["CMD-SHELL", "php-fpm --status || exit 1"]

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Chargement direct à la racine
    depends_on:
      php:
        condition: service_healthy
    networks:
      - symfony

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony: