home:
    path: /home
    controller: App\Controller\HomeController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_dashboard:
    path: /dashboard
    controller: App\Controller\PageController::dashboard
